server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active: git
#    active: native(for path or file location)
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

  cloud:
    config:
      server:
#          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/jungchechang/microservices-config.git"
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"